//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScpDriverInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScpDriverInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose to install a Bluetooth dongle but have not selected one or more devices from the device list!.
        /// </summary>
        internal static string BthListEmpty_Text {
            get {
                return ResourceManager.GetString("BthListEmpty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Bluetooth devices selected.
        /// </summary>
        internal static string BthListEmpty_Title {
            get {
                return ResourceManager.GetString("BthListEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose to install the DualShock 3 drivers but you didn&apos;t select one or more devices from the device list!.
        /// </summary>
        internal static string Ds3ListEmpta_Text {
            get {
                return ResourceManager.GetString("Ds3ListEmpta_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DualShock 3 controllers selected.
        /// </summary>
        internal static string Ds3ListEmpta_Title {
            get {
                return ResourceManager.GetString("Ds3ListEmpta_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose to install the DualShock 4 drivers but you didn&apos;t select one or more devices from the device list!.
        /// </summary>
        internal static string Ds4ListEmpta_Text {
            get {
                return ResourceManager.GetString("Ds4ListEmpta_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DualShock 4 controllers selected.
        /// </summary>
        internal static string Ds4ListEmpta_Title {
            get {
                return ResourceManager.GetString("Ds4ListEmpta_Title", resourceCulture);
            }
        }
    }
}
