//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScpDriverInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScpDriverInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! It looks like the necessary drivers are in their proper place, please proceed to the next step..
        /// </summary>
        internal static string BthInstOk_Content {
            get {
                return ResourceManager.GetString("BthInstOk_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This installation was made possible by the great &lt;a href=&quot;https://github.com/pbatard/libwdi&quot;&gt;libwdi&lt;/a&gt; library..
        /// </summary>
        internal static string BthInstOk_Footer {
            get {
                return ResourceManager.GetString("BthInstOk_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Hosts installed successfully.
        /// </summary>
        internal static string BthInstOk_Instruction {
            get {
                return ResourceManager.GetString("BthInstOk_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation successful.
        /// </summary>
        internal static string BthInstOk_Title {
            get {
                return ResourceManager.GetString("BthInstOk_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seriously, nothing to see here, everything is STILL fine! =).
        /// </summary>
        internal static string BthInstOk_Verbose {
            get {
                return ResourceManager.GetString("BthInstOk_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose to install a Bluetooth dongle but have not selected one or more devices from the device list!.
        /// </summary>
        internal static string BthListEmpty_Text {
            get {
                return ResourceManager.GetString("BthListEmpty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Bluetooth devices selected.
        /// </summary>
        internal static string BthListEmpty_Title {
            get {
                return ResourceManager.GetString("BthListEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose to install the DualShock 3 drivers but you didn&apos;t select one or more devices from the device list!.
        /// </summary>
        internal static string Ds3ListEmpty_Text {
            get {
                return ResourceManager.GetString("Ds3ListEmpty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DualShock 3 controllers selected.
        /// </summary>
        internal static string Ds3ListEmpty_Title {
            get {
                return ResourceManager.GetString("Ds3ListEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose to install the DualShock 4 drivers but you didn&apos;t select one or more devices from the device list!.
        /// </summary>
        internal static string Ds4ListEmpty_Text {
            get {
                return ResourceManager.GetString("Ds4ListEmpty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DualShock 4 controllers selected.
        /// </summary>
        internal static string Ds4ListEmpty_Title {
            get {
                return ResourceManager.GetString("Ds4ListEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry to inform you that some of your devices weren&apos;t installed properly.
        ///
        ///Sadly there are too many possibilities of why it failed to cram all suggested resolutions in one of these info boxes, but I can give you some hints on resolving the issue:
        ///
        ///1. Re-open this Driver Installer and simply try again. Seriously, try it.
        ///2. Reboot your machine. It&apos;s Windows, so it might help.
        ///3. Check your cabling. Your cat might have gnawed on your USB cable.
        ///4. Is your controller listen under &quot;Human Interface De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DsInstError_Content {
            get {
                return ResourceManager.GetString("DsInstError_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you can&apos;t resolve this issue by yourself, &lt;a href=&quot;https://github.com/nefarius/ScpToolkit/wiki&quot;&gt;check out the online documentation&lt;/a&gt;..
        /// </summary>
        internal static string DsInstError_Footer {
            get {
                return ResourceManager.GetString("DsInstError_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more installation tasks failed or did not complete.
        /// </summary>
        internal static string DsInstError_Instruction {
            get {
                return ResourceManager.GetString("DsInstError_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed.
        /// </summary>
        internal static string DsInstError_Title {
            get {
                return ResourceManager.GetString("DsInstError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer result: {0} ({1}).
        /// </summary>
        internal static string DsInstError_Verbose {
            get {
                return ResourceManager.GetString("DsInstError_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! It looks like the necessary drivers are in their proper place, please proceed to the next step..
        /// </summary>
        internal static string DsInstOk_Content {
            get {
                return ResourceManager.GetString("DsInstOk_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This installation was made possible by the great &lt;a href=&quot;https://github.com/pbatard/libwdi&quot;&gt;libwdi&lt;/a&gt; library..
        /// </summary>
        internal static string DsInstOk_Footer {
            get {
                return ResourceManager.GetString("DsInstOk_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DualShock controllers installed successfully.
        /// </summary>
        internal static string DsInstOk_Instruction {
            get {
                return ResourceManager.GetString("DsInstOk_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation successful.
        /// </summary>
        internal static string DsInstOk_Title {
            get {
                return ResourceManager.GetString("DsInstOk_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to see here, everything is fine! =).
        /// </summary>
        internal static string DsInstOk_Verbose {
            get {
                return ResourceManager.GetString("DsInstOk_Verbose", resourceCulture);
            }
        }
    }
}
