using System.Linq;
using System.Windows;
using ScpControl.Driver.PNPUtilLib;

namespace ScpCleanWipe
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private static readonly IDriverStore Store = new PnpUtil();

        public MainWindow()
        {
            InitializeComponent();
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            var storeEntries = Store.EnumeratePackages();

            var vBuses = storeEntries.Where(dse => dse.DriverPkgProvider.Equals("Scarlet.Crush Productions"));

            var usbDevices = storeEntries.Where(dse => dse.DriverSignerName.Contains("libwdi autogenerated")
                                                       && dse.DriverPkgProvider.Equals("libusbK"));
        }
    }
}
